[tool.poetry]
name = "pendulum"
version = "3.0.0a0"
description = "Python datetimes made easy"
authors = ["Sébastien Eustace <sebastien@eustace.io>"]
license = "MIT"
readme = 'README.rst'
homepage = "https://pendulum.eustace.io"
repository = "https://github.com/sdispater/pendulum"
documentation = "https://pendulum.eustace.io/docs"
keywords = ['datetime', 'date', 'time']

packages = [
    {include = "pendulum"},
    #{include = "tests", format = "sdist"},
]
include = [
    {path = "pendulum/py.typed"},
    # C extensions must be included in the wheel distributions
    {path = "pendulum/_extensions/*.so", format = "wheel"},
    {path = "pendulum/_extensions/*.pyd", format = "wheel"},
    {path = "pendulum/parsing/*.so", format = "wheel"},
    {path = "pendulum/parsing/*.pyd", format = "wheel"},
]


[tool.poetry.dependencies]
python = "^3.6"
python-dateutil = "^2.6"
"backports.zoneinfo" = {version = "^0.2.1", python = ">=3.6,<3.9"}
tzdata = ">=2020.1"

[tool.poetry.group.dev.dependencies]
pytest = "^5.4.3"
pytest-cov = "^2.5"
pytz = ">=2018.3"
babel = "^2.5"
cleo = "^1.0.0a3"
tox = "^3.0"
black = {version = "^21.9b0", markers = "python_full_version >= '3.6.2' and python_version < '4.0' and implementation_name != 'pypy'"}
isort = {version = "^5.9.1", python = "^3.6.1"}
pre-commit = {version = "^2.10.0", python = "^3.6.1"}
mkdocs = { version = "^1.0", python = "^3.5" }
pymdown-extensions = "^6.0"
pygments = "^2.2"
markdown-include = "^0.5.1"
time-machine = "^2.4.0"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"

[tool.isort]
profile = "black"
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true

known_first_party = "pendulum"
known_third_party = [
    "babel",
    "cleo",
    "dateutil",
    "time_machine",
    "pytzdata",
]


[build-system]
requires = ["poetry-core>=1.1.0a6"]
build-backend = "poetry.core.masonry.api"
